q = chr(34)
t = chr(9)
path = r'C:\Users\38389\Documents\battle-game\scripts\inventory_ui.gd'
with open(path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

insert_at = None
for i, l in enumerate(lines):
    if l.strip().startswith('func _get_slot_item'):
        insert_at = i
        break
assert insert_at is not None, 'not found'

new_sec = []
def L(s): new_sec.append(s + chr(10))

L('func _build_hotbar() -> void:')
L(t+'var cw := BAG_COLS*(SLOT_SIZE+SLOT_GAP)-SLOT_GAP + HPAD*2')
L(t+'var ch := SLOT_SIZE + VPAD*2')
L(t+'_hotbar_root = Control.new()')
L(t+'_hotbar_root.size = Vector2(cw, ch)')
L(t+'_hotbar_root.position = Vector2((_vp.x-cw)*0.5, _vp.y-ch-10.0)')
L(t+'_hotbar_root.mouse_filter = Control.MOUSE_FILTER_IGNORE')
L(t+'add_child(_hotbar_root)')
L(t+'var bg_outer := ColorRect.new()')
L(t+'bg_outer.size = Vector2(cw,ch); bg_outer.color = C_BAG_OUT')
L(t+'bg_outer.mouse_filter = Control.MOUSE_FILTER_IGNORE')
L(t+'_hotbar_root.add_child(bg_outer)')
L(t+'var bg_frame := ColorRect.new()')
L(t+'bg_frame.position = Vector2(2,2)')
L(t+'bg_frame.size = Vector2(cw-4,ch-4); bg_frame.color = C_BAG_FRAME')
L(t+'bg_frame.mouse_filter = Control.MOUSE_FILTER_IGNORE')
L(t+'_hotbar_root.add_child(bg_frame)')
L(t+'var bg_inner := ColorRect.new()')
L(t+'bg_inner.position = Vector2(4,4)')
L(t+'bg_inner.size = Vector2(cw-8,ch-8); bg_inner.color = C_HOTBAR_BG')
L(t+'bg_inner.mouse_filter = Control.MOUSE_FILTER_IGNORE')
L(t+'_hotbar_root.add_child(bg_inner)')
L(t+'var vine := VineDrawer.new()')
L(t+'vine.size = _hotbar_root.size')
L(t+'vine.mouse_filter = Control.MOUSE_FILTER_IGNORE')
L(t+'_hotbar_root.add_child(vine)')
L(t+'for i in Inventory.HOTBAR_SIZE:')
L(t+t+'var lx := HPAD + i*(SLOT_SIZE+SLOT_GAP)')
L(t+t+'_hotbar_slots.append(_make_slot(_hotbar_root, Vector2(lx,VPAD), C_SLOT_BG))')
L(t+t+'_hotbar_rects.append(Rect2(_hotbar_root.position+Vector2(lx,VPAD), Vector2(SLOT_SIZE,SLOT_SIZE)))')
L('')
L('')
L('func _build_bag() -> void:')
L(t+'var gw := BAG_COLS*(SLOT_SIZE+SLOT_GAP)-SLOT_GAP')
L(t+'var craft_extra := 2*(SLOT_SIZE+SLOT_GAP) + 32 + SLOT_SIZE + 20')
L(t+'var pw := gw + (HPAD+BORDER_W)*2 + craft_extra')
L(t+'var gh := BAG_ROWS*(SLOT_SIZE+SLOT_GAP)-SLOT_GAP')
L(t+'var ph := BORDER_W*2 + VPAD + 34 + 10 + gh + 16 + SLOT_SIZE + VPAD')
L(t+'_bag_panel = Control.new()')
L(t+'_bag_panel.size = Vector2(pw,ph)')
L(t+'_bag_panel.position = Vector2((_vp.x-pw)*0.5, (_vp.y-ph)*0.5)')
L(t+'_bag_panel.visible = false')
L(t+'_bag_panel.mouse_filter = Control.MOUSE_FILTER_STOP')
L(t+'add_child(_bag_panel)')
L(t+'var outer := ColorRect.new()')
L(t+'outer.size = Vector2(pw,ph); outer.color = C_BAG_OUT')
L(t+'outer.mouse_filter = Control.MOUSE_FILTER_IGNORE')
L(t+'_bag_panel.add_child(outer)')
L(t+'var frame := ColorRect.new()')
L(t+'frame.position = Vector2(3,3)')
L(t+'frame.size = Vector2(pw-6,ph-6); frame.color = C_BAG_FRAME')
L(t+'frame.mouse_filter = Control.MOUSE_FILTER_IGNORE')
L(t+'_bag_panel.add_child(frame)')
L(t+'var inner := ColorRect.new()')
L(t+'inner.position = Vector2(BORDER_W,BORDER_W)')
L(t+'inner.size = Vector2(pw-BORDER_W*2,ph-BORDER_W*2); inner.color = C_BAG_IN')
L(t+'inner.mouse_filter = Control.MOUSE_FILTER_IGNORE')
L(t+'_bag_panel.add_child(inner)')
L(t+'for cp in [Vector2(0,0), Vector2(pw-14,0), Vector2(0,ph-14), Vector2(pw-14,ph-14)]:')
L(t+t+'var ca := ColorRect.new()')
L(t+t+'ca.position = cp; ca.size = Vector2(14,14); ca.color = C_BAG_FRAME')
L(t+t+'ca.mouse_filter = Control.MOUSE_FILTER_IGNORE')
L(t+t+'_bag_panel.add_child(ca)')
L(t+t+'var ca2 := ColorRect.new()')
L(t+t+'ca2.position = cp+Vector2(3,3); ca2.size = Vector2(8,8); ca2.color = Color(0.75,0.52,0.12,1.0)')
L(t+t+'ca2.mouse_filter = Control.MOUSE_FILTER_IGNORE')
L(t+t+'_bag_panel.add_child(ca2)')
L(t+'var title := Label.new()')
L(t+'title.text = "\u80cc  \u5305"')
L(t+'title.position = Vector2(BORDER_W, BORDER_W+VPAD)')
L(t+'title.size = Vector2(pw-BORDER_W*2, 34)')
L(t+'title.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER')
L(t+'title.add_theme_color_override("font_color", C_TITLE)')
L(t+'title.add_theme_font_size_override("font_size", 22)')
L(t+'_bag_panel.add_child(title)')
L(t+'var sep_top := ColorRect.new()')
L(t+'sep_top.position = Vector2(BORDER_W, BORDER_W+VPAD+34+4)')
L(t+'sep_top.size = Vector2(pw-BORDER_W*2, 2); sep_top.color = C_SEP')
L(t+'sep_top.mouse_filter = Control.MOUSE_FILTER_IGNORE')
L(t+'_bag_panel.add_child(sep_top)')
L(t+'var close_btn := Button.new()')
L(t+'close_btn.text = "x"')
L(t+'close_btn.position = Vector2(pw-BORDER_W-30, BORDER_W+6)')
L(t+'close_btn.size = Vector2(26,26)')
L(t+'close_btn.flat = true')
L(t+'close_btn.add_theme_color_override("font_color", C_TITLE)')
L(t+'close_btn.pressed.connect(_toggle_bag)')
L(t+'_bag_panel.add_child(close_btn)')
L(t+'var vine := VineDrawer.new()')
L(t+'vine.size = _bag_panel.size')
L(t+'vine.mouse_filter = Control.MOUSE_FILTER_IGNORE')
L(t+'_bag_panel.add_child(vine)')
L(t+'var gx := BORDER_W + HPAD')
L(t+'var gy := BORDER_W + VPAD + 34 + 10')
L(t+'for row in BAG_ROWS:')
L(t+t+'for col in BAG_COLS:')
L(t+t+t+'var lx := gx + col*(SLOT_SIZE+SLOT_GAP)')
L(t+t+t+'var ly := gy + row*(SLOT_SIZE+SLOT_GAP)')
L(t+t+t+'_bag_slots.append(_make_slot(_bag_panel, Vector2(lx,ly), C_BAG_SLOT))')
L(t+t+t+'_bag_rects.append(Rect2(_bag_panel.position+Vector2(lx,ly), Vector2(SLOT_SIZE,SLOT_SIZE)))')
L(t+'var sep := ColorRect.new()')
L(t+'sep.position = Vector2(gx, gy+gh+7)')
L(t+'sep.size = Vector2(gw,2); sep.color = C_SEP')
L(t+'sep.mouse_filter = Control.MOUSE_FILTER_IGNORE')
L(t+'_bag_panel.add_child(sep)')
L(t+'var bh_y := gy+gh+14')
L(t+'for i in Inventory.HOTBAR_SIZE:')
L(t+t+'var lx := gx+i*(SLOT_SIZE+SLOT_GAP)')
L(t+t+'_bh_slots.append(_make_slot(_bag_panel, Vector2(lx,bh_y), C_BAG_SLOT))')
L(t+t+'_bh_rects.append(Rect2(_bag_panel.position+Vector2(lx,bh_y), Vector2(SLOT_SIZE,SLOT_SIZE)))')
L(t+'_build_craft_inside_bag(gx, gy, gw)')
L('')
L('')
L('func _build_craft_inside_bag(gx:int, gy:int, gw:int) -> void:')
L(t+'var cx_start := gx + gw + 16')
L(t+'var cy_start := gy')
L(t+'var lbl := Label.new()')
L(t+'lbl.text = "\u88fd  \u4f5c"')
L(t+'lbl.position = Vector2(cx_start, cy_start - 24)')
L(t+'lbl.size = Vector2(2*(SLOT_SIZE+SLOT_GAP)+20, 20)')
L(t+'lbl.add_theme_color_override("font_color", C_TITLE)')
L(t+'lbl.add_theme_font_size_override("font_size", 14)')
L(t+'_bag_panel.add_child(lbl)')
L(t+'for i in 4:')
L(t+t+'var col := i % 2')
L(t+t+'var row := i / 2')
L(t+t+'var lx := cx_start + col*(SLOT_SIZE+SLOT_GAP)')
L(t+t+'var ly := cy_start + row*(SLOT_SIZE+SLOT_GAP)')
L(t+t+'_craft_slots.append(_make_slot(_bag_panel, Vector2(lx,ly), C_CRAFT_SLOT))')
L(t+t+'_craft_rects.append(Rect2(_bag_panel.position+Vector2(lx,ly), Vector2(SLOT_SIZE,SLOT_SIZE)))')
L(t+'var arrow_lbl := Label.new()')
L(t+'arrow_lbl.text = "\u2192"')
L(t+'arrow_lbl.position = Vector2(cx_start + 2*(SLOT_SIZE+SLOT_GAP)+2, cy_start + SLOT_SIZE*0.5 - 12)')
L(t+'arrow_lbl.size = Vector2(28, 28)')
L(t+'arrow_lbl.add_theme_color_override("font_color", C_TITLE)')
L(t+'arrow_lbl.add_theme_font_size_override("font_size", 22)')
L(t+'_bag_panel.add_child(arrow_lbl)')
L(t+'var rx := cx_start + 2*(SLOT_SIZE+SLOT_GAP) + 32')
L(t+'var ry := cy_start + SLOT_SIZE*0.5 - SLOT_SIZE*0.5')
L(t+'_craft_result_slot = _make_slot(_bag_panel, Vector2(rx,ry), C_CRAFT_SLOT)')
L(t+'_craft_result_rect = Rect2(_bag_panel.position+Vector2(rx,ry), Vector2(SLOT_SIZE,SLOT_SIZE))')
L('')
L('')
L('func _build_drag_icon() -> void:')
L(t+'_drag_icon = Control.new()')
L(t+'_drag_icon.size = Vector2(SLOT_SIZE, SLOT_SIZE)')
L(t+'_drag_icon.visible = false')
L(t+'_drag_icon.mouse_filter = Control.MOUSE_FILTER_IGNORE')
L(t+'_drag_icon.z_index = 100')
L(t+'add_child(_drag_icon)')
L(t+'_drag_bg = ColorRect.new()')
L(t+'_drag_bg.size = Vector2(SLOT_SIZE, SLOT_SIZE)')
L(t+'_drag_bg.color = Color(0.4, 0.3, 0.1, 0.7)')
L(t+'_drag_bg.mouse_filter = Control.MOUSE_FILTER_IGNORE')
L(t+'_drag_icon.add_child(_drag_bg)')
L(t+'_drag_draw = ItemIconDrawer.new()')
L(t+'_drag_draw.size = Vector2(SLOT_SIZE, SLOT_SIZE)')
L(t+'_drag_draw.mouse_filter = Control.MOUSE_FILTER_IGNORE')
L(t+'_drag_icon.add_child(_drag_draw)')
L(t+'_drag_lbl = Label.new()')
L(t+'_drag_lbl.size = Vector2(SLOT_SIZE, SLOT_SIZE)')
L(t+'_drag_lbl.horizontal_alignment = HORIZONTAL_ALIGNMENT_RIGHT')
L(t+'_drag_lbl.vertical_alignment = VERTICAL_ALIGNMENT_BOTTOM')
L(t+'_drag_lbl.add_theme_color_override("font_color", C_TEXT)')
L(t+'_drag_lbl.add_theme_font_size_override("font_size", 14)')
L(t+'_drag_lbl.mouse_filter = Control.MOUSE_FILTER_IGNORE')
L(t+'_drag_icon.add_child(_drag_lbl)')
L('')
L('')
L('func _make_slot(parent: Control, pos: Vector2, bg_col: Color) -> Dictionary:')
L(t+'var c := Control.new()')
L(t+'c.position = pos')
L(t+'c.size = Vector2(SLOT_SIZE, SLOT_SIZE)')
L(t+'c.mouse_filter = Control.MOUSE_FILTER_IGNORE')
L(t+'parent.add_child(c)')
L(t+'var bg := ColorRect.new()')
L(t+'bg.size = Vector2(SLOT_SIZE, SLOT_SIZE); bg.color = bg_col')
L(t+'bg.mouse_filter = Control.MOUSE_FILTER_IGNORE')
L(t+'c.add_child(bg)')
L(t+'var bor := ColorRect.new()')
L(t+'bor.size = Vector2(SLOT_SIZE, SLOT_SIZE); bor.color = C_SLOT_BOR')
L(t+'bor.mouse_filter = Control.MOUSE_FILTER_IGNORE')
L(t+'c.add_child(bor)')
L(t+'var bor2 := ColorRect.new()')
L(t+'bor2.position = Vector2(2,2)')
L(t+'bor2.size = Vector2(SLOT_SIZE-4, SLOT_SIZE-4); bor2.color = bg_col')
L(t+'bor2.mouse_filter = Control.MOUSE_FILTER_IGNORE')
L(t+'c.add_child(bor2)')
L(t+'var draw := ItemIconDrawer.new()')
L(t+'draw.position = Vector2(4,4)')
L(t+'draw.size = Vector2(SLOT_SIZE-8, SLOT_SIZE-8)')
L(t+'draw.mouse_filter = Control.MOUSE_FILTER_IGNORE')
L(t+'c.add_child(draw)')
L(t+'var lbl := Label.new()')
L(t+'lbl.size = Vector2(SLOT_SIZE-2, SLOT_SIZE-2)')
L(t+'lbl.horizontal_alignment = HORIZONTAL_ALIGNMENT_RIGHT')
L(t+'lbl.vertical_alignment = VERTICAL_ALIGNMENT_BOTTOM')
L(t+'lbl.add_theme_color_override("font_color", C_TEXT)')
L(t+'lbl.add_theme_font_size_override("font_size", 14)')
L(t+'lbl.mouse_filter = Control.MOUSE_FILTER_IGNORE')
L(t+'c.add_child(lbl)')
L(t+'var sel := ColorRect.new()')
L(t+'sel.size = Vector2(SLOT_SIZE, SLOT_SIZE); sel.color = Color(0,0,0,0)')
L(t+'sel.mouse_filter = Control.MOUSE_FILTER_IGNORE')
L(t+'c.add_child(sel)')
L(t+'return {"root": c, "bg": bg, "draw": draw, "lbl": lbl, "sel": sel}')
L('')
L('')
L('func _refresh() -> void:')
L(t+'for i in Inventory.HOTBAR_SIZE:')
L(t+t+'_update_slot(_hotbar_slots[i], Inventory.hotbar[i], i == Inventory.selected_slot)')
L(t+'if _bag_open:')
L(t+t+'for i in Inventory.BAG_SIZE:')
L(t+t+t+'_update_slot(_bag_slots[i], Inventory.bag[i], false)')
L(t+t+'for i in Inventory.HOTBAR_SIZE:')
L(t+t+t+'_update_slot(_bh_slots[i], Inventory.hotbar[i], i == Inventory.selected_slot)')
L(t+t+'_refresh_craft()')
L('')
L('')
L('func _update_slot(slot: Dictionary, item: ItemData, selected: bool) -> void:')
L(t+'slot["draw"].set_item(item.item_id if item != null else "")')
L(t+'slot["lbl"].text = str(item.quantity) if (item != null and item.quantity > 1) else ""')
L(t+'slot["sel"].color = C_SEL if selected else Color(0,0,0,0)')
L('')
L('')

result = lines[:insert_at] + new_sec + lines[insert_at:]
with open(path, 'w', encoding='utf-8') as f:
    f.writelines(result)
print('done, total lines:', len(result))
